<?php
/**
 * User: shamim
 * Date: 10/17/16
 * Time: 11:19 AM
 */

namespace App;

use App\EmployeeRolesPermission;


Class permission {

public static $perms = array(
1 => 'dashboard',
2 => 'departments',
3 => 'designations',
4 => 'Academic-Details',
5 => 'create-Institution',
6 => 'student-import',
7 => 'employee-import',
8 => 'employee-applicant',
9 => 'application-list',
10 => 'add-course',
11 => 'add-batch',
12 => 'classTeacher-Allocation',
13 => 'subject/create',
14 => 'subject/assign-subject',
15 => 'subject/subject-allocation',
16 => 'hr/employee',
17 => 'hr/employee/add',
18 => 'hr/employee/list',
19 => 'hr/employee/update',
20 => 'hr/employee/delete',
21 => 'hr/add-userType',
22 => 'hr/add-userType-new',
23 => 'hr/employee/bank-details',
24 => 'hr/employee/attendance-import',
25 => 'student/category',
26 => 'student/admission',
27 => 'student/list',
28 => 'student/attendance',
29 => 'student/transport',
30 => 'student/hostel',
31 => 'student/gaurdianlist',
32 => 'finance/Fee-Category',
33 => 'finance/Fee-SubCategory',
34 => 'finance/Fee-SubCategory/fine',
35 => 'finance/Fee-wavier',
36 => 'finance/Fee-template',
37 => 'finance/Fee-Allocation',
38 => 'finance/Fee-report',
39 => 'finance/Fee-import',
40 => 'transport/vehicle',
41 => 'transport/vehicle/add',
42 => 'transport/vehicle/update',
43 => 'transport/vehicle/delete',
44 => 'transport/driver',
45 => 'transport/driver/add',
46 => 'transport/driver/delete',
47 => 'transport/driver/view',
48 => 'transport/driver/update',
49 => 'transport/route',
50 => 'transport/route/add',
51 => 'transport/route/view',
52 => 'transport/route/update',
53 => 'transport/route/delete',
54 => 'transport/destination',
55 => 'transport/destination/add',
56 => 'transport/destination/view',
57 => 'transport/destination/update',
58 => 'transport/destination/delete',
59 => 'employee-roles',
60 => 'student/delete',
61 => 'student/view',
62 => 'student/update',
63 => 'hr/department/delete',
64 => 'hr/department/delete',
65 => 'hr/delete/degination',
66 => 'finance/Fee-Category/delete',
67 => 'finance/Fee-Sub-Category/delete',
68 => 'finance/Fee-Sub-Category-fine/delete',
69=>'Academic-session',
70 =>'announcement/teacher',
71=>'announcement/parents',
72=>'FrontOffice/office_setup',
73=>'FrontOffice/admission_enquiry',
74=>'FrontOffice/visitor_book',
75=>'FrontOffice/phone_call',
76=>'FrontOffice/postal_dispatch',
77=>'FrontOffice/postal_recieve',
78=>'FrontOffice/complain',
79=>'subject/lession-planning',
81=>'period_master',
82=>'create_timetable',
83=>'active_timetable',
84=>'batch_timetable',
85=>'teacher_timetable',
86=>'homework/homeworklist',
87=>'homework/evaluation_report',
88=>'hr/department',
89=>'hr/designation',
90=>'hr/category',
91=>'student/roll_section',
92=>'student/attendance/attendancereport',
93=>'student/gaurdian_list',
94=>'student/student_get_pass',
95=>'student/student_get_pass_list',
96=>'student/DomicileCertificat',
97=>'student/trialCertificate',
98=>'student/CharacterCertificate',
99=>'student/BonafideCertificate',
100=>'student/LeavingCertificate',
101=>'finance/Fee-master',
102=>'finance/fee/waiver',
103=>'finance/Fee/fee-Collection',
104=>'finance/Fee/feeCollection/list',
105=>'finance/Fee-collection/reports',
106=>'finance/Fee/duereport',
107=>'finance/account/account-group',
108=>'finance/account/voucher-master',
109=>'finance/account/voucher-head',
110=>'finance/account/voucher',
111=>'finance/account/voucher/list',
112=>'finance/account/voucher/daybook',
113=>'finance/account/voucher/legder-account',
114=>'finance/account/voucher/trial-account',
115=>'Exam/exam_list',
116=>'Exam/exam_schedule_list',
117=>'Exam/mark_register',
118=>'Exam/personality_traits',
119=>'Exam/monthly/mark/register',
120=>'Exam/mark_grade',
121=>'Exam/student_exam_report',
122=>'Exam/final_result',
123=>'library/category',
124=>'library/books',
125=>'library/books/issue',
126=>'library/books/book_request',
127=>'library/bookissue/return',
128=>'x',
129=>'transport/allocation/list',
130=>'hostel/details',
131=>'hostel/room',
132=>'hostel/allocation',
134=>'hostel/request/details',
135=>'hostel/transfer/vacate',
136=>'hostel/register',
137=>'hostel/visitors',
138=>'hostel/fee/collection',
139=>'hostel/details/report',
140=>'hostel/room/availability/report',
141=>'hostel/room/request/report',
142=>'hostel/room/occupancy/report',
143=>'hostel/fee/reports',
144=>'stock/issue_item',
145=>'stock/add_item_stock',
146=>'stock/add_item',
147=>'stock/item_category',
148=>'stock/item_store',
149=>'stock/item_supplier',
150=>'add-event',
151=>'event-report',
152=>'Leave-Management',

1000 =>'Dashbord-Admin',
1001 =>'Dashbord-other',
1002 =>'Settings',
1003 =>'Annoncement',
1004 =>'Front-Office',
1005 =>'Academic',
1006 =>'Acadmic/class & section',
1007 =>'Acadmic/Subject',
1008 =>'Acadmic -> Lession Planning',
1009 =>'Acadmic -> Lession Planning->Lession Planning',
1010 =>'Acadmic -> Lession Planning->View Lession Planning',
1011 =>'Time-Table',
1012 =>'Home Work & Assignments',
1013 =>'HR/Payroll',
1014 =>'HR/Payroll -> Employee management',
1015 =>'Students',
1016 =>'Finance',
1017 =>'Finance->Fee',
1018 =>'Finance->Accounting',
1019 =>'Examination',
1020 =>'Library',
1021 =>'Transport',
1022 =>'Hostel',
1023 =>'Stock',
1024 =>'Feedback',
1025 =>'Events',
);


    public static function permitted ($page) {

        $perms=self::$perms;
        $permid = array_search($page, $perms);

        $role = \Auth::user()->user_role;

        $permcheck = EmployeeRolesPermission::where('role_id', $role)->where('perm_id', $permid)->first();

        if ($permcheck==NULL){
            return 'access denied';
        }else{
            if ($permcheck->perm_id<0){
                return 'access denied';
            }else{
                return 'access granted';
            }
        }

    }
}
